In [4]:
from __future__ import print_function
import os
data_path = ['.']

In [13]:
import pandas as pd

# Import the data using the file path
filepath = os.sep.join(data_path + ['Mobile-Phones.csv'])
data = pd.read_csv(filepath)
data

,brand,model,sd_card,main_camera,resolution,display,sim_card,os,color,region,location,screen_size(inch),battery(mAh),storage(GB),ram(GB),selfie_camera(MP),price(¢)
0,Samsung,Galaxy S10,yes,"3 Cameras: 12, 12, 16 MP",1440 x 3040,AMOLED,Single,Android,White,Greater Accra,Circle,6.10,3400.0,128.0,8.0,10.0,2450.0
1,Samsung,Galaxy Note 20 Ultra,yes,"3 Cameras: 108, 12, 12 MP",1440 x 3088,AMOLED,Dual,Android,Bronze,Greater Accra,Circle,6.90,4500.0,128.0,12.0,10.0,5000.0
2,Samsung,Galaxy A54 5G,yes,"3 Cameras: 50, 12, 5 MP",1080 x 2340,Super AMOLED,Dual,Android,Black,Greater Accra,Accra Metropolitan,6.40,5000.0,256.0,8.0,32.0,3000.0
3,Tecno,Camon 20 Pro,no,"2 Cameras: 64, 2 MP",1080 x 2400,AMOLED,Dual,Android,Black,Greater Accra,Accra Metropolitan,6.67,5000.0,256.0,8.0,32.0,1900.0
4,Samsung,Galaxy S22 Ultra,no,"4 Cameras: 108, 10, 10, 12 MP",1400 x 3088,AMOLED,Dual,Android,Black,Greater Accra,Accra Metropolitan,6.80,5000.0,512.0,12.0,40.0,5750.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,Samsung,Galaxy Note 20 5G,no,TRIPLE 12MP / 64MP / 12MP,1080 x 2400,AMOLED,NaN,Android,Orange,Greater Accra,Accra Metropolitan,NaN,4300.0,128.0,NaN,10.0,2850.0
3596,LG,Stylo 6,yes,"3 Cameras: 13, 5, 5 MP",1080 x 2460,IPS,Nano-SIM,Android,Other,Ashanti,Kumasi Metropolitan,5.10,4000.0,64.0,8.0,13.0,1060.0
3597,Other Brand,Other Models,no,NaN,NaN,NaN,NaN,NaN,Black,Greater Accra,Circle,4.00,NaN,32.0,2.0,NaN,880.0
3598,Nokia,110,yes,1 Cameras: 03 MP,128 x 160,TFT,Dual,NaN,Black,Greater Accra,Circle,4.00,1020.0,4.0,NaN,NaN,299.0
3599,Apple,iPhone 13 Pro,no,1 Cameras: 12 MP,1170 x 2532,OLED,Single,IOS,Black,Greater Accra,Circle,5.10,3095.0,256.0,16.0,12.0,11500.0

In [14]:
data.head(1).T

                                          0
brand                               Samsung
model                            Galaxy S10
sd_card                                 yes
main_camera        3 Cameras: 12, 12, 16 MP
resolution                      1440 x 3040
display                              AMOLED
sim_card                             Single
os                                  Android
color                                 White
region                        Greater Accra
location                             Circle
screen_size(inch)                       6.1
battery(mAh)                         3400.0
storage(GB)                           128.0
ram(GB)                                 8.0
selfie_camera(MP)                      10.0
price(¢)                             2450.0

In [17]:
data.drop(['sd_card', 'main_camera', 'resolution','sim_card','region','location','selfie_camera(MP)','brand','display','os','color'], axis=1, inplace=True)
data

,model,screen_size(inch),battery(mAh),storage(GB),ram(GB),price(¢)
0,Galaxy S10,6.10,3400.0,128.0,8.0,2450.0
1,Galaxy Note 20 Ultra,6.90,4500.0,128.0,12.0,5000.0
2,Galaxy A54 5G,6.40,5000.0,256.0,8.0,3000.0
3,Camon 20 Pro,6.67,5000.0,256.0,8.0,1900.0
4,Galaxy S22 Ultra,6.80,5000.0,512.0,12.0,5750.0
...,...,...,...,...,...,...
3595,Galaxy Note 20 5G,NaN,4300.0,128.0,NaN,2850.0
3596,Stylo 6,5.10,4000.0,64.0,8.0,1060.0
3597,Other Models,4.00,NaN,32.0,2.0,880.0
3598,110,4.00,1020.0,4.0,NaN,299.0
3599,iPhone 13 Pro,5.10,3095.0,256.0,16.0,11500.0

In [18]:
data.columns

Index(['model', 'screen_size(inch)', 'battery(mAh)', 'storage(GB)', 'ram(GB)',
       'price(¢)'],
      dtype='object')

In [23]:
# Import label encoder 
from sklearn.preprocessing import LabelEncoder

# label_encoder object knows 
# how to understand word labels. 
lb = preprocessing.LabelEncoder() 

for col in ['model']:
    data[col] = lb.fit_transform(data[col])

NameError: name 'df' is not defined

In [22]:
import warnings
warnings.filterwarnings('ignore', module='sklearn')

from sklearn.preprocessing import MinMaxScaler

msc = MinMaxScaler()

data = pd.DataFrame(msc.fit_transform(data),  # this is an np.array, not a dataframe.
                    columns=data.columns)
data

      model  screen_size(inch)  battery(mAh)  storage(GB)   ram(GB)  price(¢)
0       0.0           0.741379      0.444444     0.121569  0.466667  0.088169
1       0.0           0.879310      0.614198     0.121569  0.733333  0.184250
2       0.0           0.793103      0.691358     0.247059  0.466667  0.108892
3       0.0           0.839655      0.691358     0.247059  0.466667  0.067445
4       0.0           0.862069      0.691358     0.498039  0.733333  0.212509
...     ...                ...           ...          ...       ...       ...
3595    0.0                NaN      0.583333     0.121569       NaN  0.103240
3596    0.0           0.568966      0.537037     0.058824  0.466667  0.035795
3597    0.0           0.379310           NaN     0.027451  0.066667  0.029013
3598    0.0           0.379310      0.077160     0.000000       NaN  0.007121
3599    0.0           0.568966      0.397377     0.247059  1.000000  0.429164

[3600 rows x 6 columns]